services:
  - type: web
    name: face-recognition-app
    runtime: docker
    plan: free # Use the free tier
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # User will provide this in the dashboard
      - key: CLIENT_ORIGIN
        value: https://face-recognition-app-20sd.onrender.com
